khadas/khadas_docs

- source/edge/HowtoBootIntoUpgradeMode.md
- source/edge/SetupSerialTool.md
- source/vim1/BuildBootLogoForUboot.md
- source/vim1/SetupSerialTool.md
- source/vim1/SetupTFTPServer.md
- source/zh-cn/edge/SetupSerialTool.md
- source/zh-cn/vim1/BuildBootLogoForUboot.md
- source/zh-cn/vim1/SetupSerialTool.md
- source/zh-cn/vim1/SetupTFTPServer.md
These commits fix some links in the Edge documentation and improve some commands in both Edge and VIMs documentations
> Some fixes and improvements

- source/faq/index.md
Added VIM3, Fixed Edge Power Specifications
> Added VIM3, Fixed Edge Power Specifications

- source/edge/ConnectLcd.md
Content extracted from: https://forum.khadas.com/t/instructions-for-edge-hdmi-mipi-dp/4614
> Added Content

- source/edge/SetupSerialTool.md
Reduce confusion between Edge-V and Edge.
> Updated Serial Debug Tool For Edge-V

- source/edge/FirmwareUbuntu.md
- source/vim1/FirmwareUbuntu.md
- source/vim2/FirmwareUbuntu.md
- source/vim3/FirmwareUbuntu.md
1. Update Ubuntu Firmware Version && Release
by frank<frank@khadas.com>
> Ubuntu firmware update

- source/zh-cn/edge/FirmwareUbuntu.md
- source/zh-cn/vim1/FirmwareUbuntu.md
- source/zh-cn/vim2/FirmwareUbuntu.md
- source/zh-cn/vim3/FirmwareUbuntu.md
Edge VIM1 VIM2 VIM3
1. Update Ubuntu Firmware && Release with zh-cn
by frank<frank@khadas.com>
> update ubuntu firmware with zh-cn

- source/vim1/BootFromExtMedia.md
- source/zh-cn/vim1/BootFromExtMedia.md
VIM1 VIM2 VIM3
1. Update external media startup instructions
for frank<frank@khadas.com>
> update external media startup instaruction

- source/vim3/HardwareDocs.md
Added files from: https://dl.khadas.com/Hardware/VIM3/CAD/VIM3%20v12%203D%20CAD%2009-Sep-2019.zip
> Added 3D CAD Files for VIM3/3L

- source/vim3/HardwareDocs.md
3705 Cooling Fan, New VIM Heatsink, TS050 Touchscreen
> Added 3D CAD Files for VIM3/3L Accessories

- source/vim1/BootFromExtMedia.md
The current version does not correspond with Armbian or LibreELEC. Feel free to do any changes as you see fit.
> Update "Boot Images from External Media" guide

- source/vim1/BootFromExtMedia.md
Updated again with some small changes and more information regarding if another OS than Android, Armbian or LibreELEC has been installed to eMMC.
> Update Boot Images from External Media

- source/vim3/HardwareDocs.md
> Updated 3D CAD Files (VIM3/3L)

- source/edge/HardwareDocs.md
> Updated 3D CAD Files (Edge, Edge-V)

- source/vim3/FirmwareThirdparty.md
Add more Manjaro editions to vim3/FirmwareThirdParty.md
> Add more Manjaro editions

- source/vim1/index.md
```Note: Please do not attach multiple cables with large heads that interfere with each other, as that may bend or twist the connectors, and this will cause intermittent connectivity issues after some time.```
> Updated Port Stuffing Issue for VIM1

- source/edge/index.md
```Note: Please do not attach multiple cables with large heads that interfere with each other, as that may bend or twist the connectors, and this will cause intermittent connectivity issues after some time.```
> Added Note for Port-Stuffing Issue

- source/vim3/index.md
```Note: Please do not attach multiple cables with large heads that interfere with each other, as that may bend or twist the connectors, and this will cause intermittent connectivity issues after some time.```
> Added Port Stuffing Issue for VIM3

- source/vim2/index.md
```Note: Please do not attach multiple cables with large heads that interfere with each other, as that may bend or twist the connectors, and this will cause intermittent connectivity issues after some time.```
> Updated for Port Stuffing Issue for VIM2

- source/_data/sidebar.yml
- source/vim3/HowToTrainInception.md
- source/zh-cn/vim3/HowToTrainInception.md
- themes/navy/languages/en.yml
- themes/navy/languages/zh-cn.yml
How to train inception model
by frank <frank@khadas.com>
> Add How to train inception model

- source/edge/index.md
- Added labelled product diagrams
- Added links to relevant pages
> Update Edge Beginners Guide

- source/vim3/index.md
Big update for VIM3's documentation.
> Updated Beginners Guide (NPU, Diagrams)

- source/vim2/index.md
> Big Update to VIM2's Beginner Guide

- source/vim1/index.md
> Big Update to VIM1's Beginner Guide

- source/vim1/HowtoBootIntoUpgradeMode.md
> Added TST Mode for VIM1 v14!

- source/vim1/index.md
Updated as per Gouwa's recommendations.
> Updated VIM1 Beginner's Guide

- source/vim2/index.md
Updated as per Gouwa's instructions.
> Updated VIM2's Beginner Guide

- source/vim3/index.md
Updated as per Gouwa's instructions.
> Updated VIM3 / 3L Beginner's Guide

- source/edge/index.md
Updated as per Gouwa's instructions.
> Updated Edge Beginner's Guide

- source/vim3/index.md
Some new users don't know how to upgrade VIM3's OS....
> Added OS Upgrading to VIM3 Beginner's Guide

- source/vim3/index.md
Remember to also update the picture!
> Updated Krescue Docs (Online Updating for VIM3)

- source/vim2/index.md
Remember to also update the picture!
> Updated Krescue Docs (Online Updating for VIM2)

- source/vim1/index.md
Remember to also update the picture!
> Updated Krescue Docs (Online Updating for VIM1)

- source/vim1/BuildBootLogoForUboot.md
U-Boot Usage ---> Setup Serial Tool
> Updated Link for U-Boot Usage to Setup Serial Tool

- source/vim1/SetupSerialTool.md
Added more detailed instructions for beginner users, on how to use U-Boot.
> Clarified Instructions for "Entering U-Boot"

- source/vim1/SetupSerialTool.md
Press space-bar or control-c to stop auto-boot.
> Updated U-Boot Instructions (impt!)

- source/vim3/HowtoBootIntoUpgradeMode.md
/images/vim3/VIM3_M_Register.jpg
> Added Picture for VIM3's M-Register

- source/vim3/HowToInstallDarknet.md
- source/zh-cn/vim3/HowToInstallDarknet.md
- themes/navy/languages/en.yml
> Typo, rename darnket to darknet.

- source/vim1/HowToWriteSDImageToEmmc.md
Burn to Image now points to: https://dl.khadas.com/Firmware/
> Updated Firmware Link

- source/tone1/HowtoUpgradeFirmware.md
> Updated Instructions for Tone2 Pro

- source/vim1/HowToUse1wire.md
- source/zh-cn/vim1/HowToUse1wire.md
> Add onewire phy pins to onewire docs

- source/tone1/HowtoUpgradeFirmware.md
chmod +x ./tone_dfu_tool_macos
and
https://dl.khadas.com/products/tone2/dfu_tool/tone_dfu_tool_macos
> Updated Mac OS X Instructions

- source/vim1/SetupSerialTool.md
- source/zh-cn/vim1/SetupSerialTool.md
add serial tool lines description
> add serial tool lines description

- source/_data/sidebar.yml
- source/vim1/HowToRotateFramebuffer.md
- source/vim2/HowToRotateFramebuffer.md
- source/vim3/HowToRotateFramebuffer.md
- source/vim3/UbuntuLandscapeSettings.md
- source/zh-cn/vim1/HowToRotateFramebuffer.md
- source/zh-cn/vim2/HowToRotateFramebuffer.md
- source/zh-cn/vim3/HowToRotateFramebuffer.md
- source/zh-cn/vim3/UbuntuLandscapeSettings.md
- themes/navy/languages/en.yml
- themes/navy/languages/zh-cn.yml
1. framebuffer rotate docs
2. modified ts050 landscape docs
> update docs for screen

- source/vim1/HowToRotateFramebuffer.md
- source/vim3/UbuntuLandscapeSettings.md
- source/zh-cn/vim1/HowToRotateFramebuffer.md
- source/zh-cn/vim3/UbuntuLandscapeSettings.md
> Optimize How To Rotate Framebuffer && Landscape Settings docs

- source/vim1/Krescue.md
- source/zh-cn/vim1/Krescue.md
It improves the related contents of krescue document, mainly how to use krescue's options and other ambiguous parts.
> It improves the related contents of krescue document, mainly how to use krescue's options and other ambiguous parts.

- source/tone1/HowtoUpgradeFirmware.md
Added x3 new videos for customers.
> Updated Tone Board Firmware Upgrade Instructions

- source/vim3/HowToUseAndroidNpuDemo.md
- source/vim3/HowToUseNpuJni.md
- source/zh-cn/vim3/HowToUseAndroidNpuDemo.md
- source/zh-cn/vim3/HowToUseNpuJni.md
Signed-off-by: jason <jason@khadas.com>
> modify github address

- source/vim1/HowToConfigureWi-FiToWorkInSTA+APMode.md
- source/zh-cn/vim1/HowToConfigureWi-FiToWorkInSTA+APMode.md
> Add 5G hostpspot setting to HowToConfigureWi-FiToWorkInSTA+APMode.md

- android/scripts
- android/scripts/helpers.js
- android/scripts/tags.js
- android/scripts/toc.js
> Firmware: Fixup editor error

- public/vim3/index.html
- public/zh-cn/vim3/index.html
> Restore some old index.html

- .github/workflows/main.yaml
- public/android/vim1/AccessI2c_android.html
- public/android/vim2/AccessI2c_android.html
- public/android/vim3/AccessI2c_android.html
- public/android/zh-cn/vim1/AccessI2c_android.html
- public/android/zh-cn/vim2/AccessI2c_android.html
- public/android/zh-cn/vim3/AccessI2c_android.html
> Android Docs: Add AccessI2C_android docs, link to AccessI2C docs

- .github/workflows/main.yaml
> Fixup action error

- linux/source/vim1/index.md
Edited English of the quickstart guide.
> Corrected: English + Layout

- linux/source/vim1/OsIntroduce.md
> Corrected: English & Layout of the OS Introduction

- linux/source/vim2/index.md
> Updated VIM2 Quickstart

- linux/source/vim2/OsIntroduce.md
> Updated VIM2 - Choose an OS

- linux/source/vim3/index.md
> Updated VIM3 - Quickstart

- linux/source/vim3/OsIntroduce.md
> Updated VIM3 - Choose an OS

- linux/source/vim3/MIPICamera.md
- linux/source/zh-cn/edge/index.md
- linux/source/zh-cn/vim3/MIPICamera.md
> Linux Docs: Update MIPICamera c++ demo for opencv4

- linux/source/_data/sidebar.yml
- linux/source/firmware/EdgeUbuntuFirmware.md
- linux/source/firmware/Vim1UbuntuFirmware.md
- linux/source/firmware/Vim2UbuntuFirmware.md
- linux/source/firmware/Vim3UbuntuFirmware.md
- linux/source/vim3/KSNNAPI.md
- linux/source/vim3/KSNNConvert.md
- linux/source/vim3/KSNNUsage.md
- linux/source/zh-cn/firmware/EdgeUbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim1UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim2UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim3UbuntuFirmware.md
- linux/source/zh-cn/vim3/KSNNAPI.md
- linux/source/zh-cn/vim3/KSNNConvert.md
- linux/source/zh-cn/vim3/KSNNUsage.md
- linux/themes/navy/languages/en.yml
- linux/themes/navy/languages/zh-cn.yml
> Linux Docs: Add KSNN Docs

- linux/source/vim1/SoftPWMServo.md
- linux/source/zh-cn/vim1/SoftPWMServo.md
Signed-off-by: Frank Wang <frank@khadas.com>
> Linux Docs: VIM1/VIM2/VIM3: Remove Servo gif in SoftPWM demo

- linux/source/_data/sidebar.yml
- linux/source/vim3/SPIUsage.md
- linux/source/zh-cn/vim3/SPIUsage.md
- linux/themes/navy/languages/en.yml
- linux/themes/navy/languages/zh-cn.yml
Signed-off-by: Frank Wang <frank@khadas.com>
> Linux Docs: VIM3: Add SPI Usage docs

- public/vim1/HowToWriteSDImageToEmmc.html
- public/vim2/HowToWriteSDImageToEmmc.html
- public/vim3/HowToWriteSDImageToEmmc.html
- public/zh-cn/vim1/HowToWriteSDImageToEmmc.html
- public/zh-cn/vim2/HowToWriteSDImageToEmmc.html
- public/zh-cn/vim3/HowToWriteSDImageToEmmc.html
Signed-off-by: Frank Wang <frank@khadas.com>
> pubilc: Repair old link 'HowToWriteSDImageToEmmc.html' loss

- linux/source/firmware/Vim1UbuntuFirmware.md
- linux/source/firmware/Vim2UbuntuFirmware.md
- linux/source/firmware/Vim3UbuntuFirmware.md
- linux/source/firmware/Vim3lUbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim1UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim2UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim3UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim3lUbuntuFirmware.md
Signed-off-by: Frank Wang <frank@khadas.com>
> docs: linux: VIMs: fixup 1217 release link error

- android/source/vim4/app_platform_sign.md
Signed-off-by: Yan Wang <frank@khadas.com>
> docs: android: vim4: fix link error in app platform sign doc

- linux/source/hardware/hardwareVim4.md
- linux/source/zh-cn/hardware/hardwareVim4.md
Signed-off-by: Yan Wang <frank@khadas.com>
> docs: update hardware docs link

- android/source/hardware/hardwareVim4.md
- android/source/zh-cn/hardware/hardwareVim4.md
Signed-off-by: Yan Wang <frank@khadas.com>
> docs: android: update hardware docs link

- linux/source/firmware/EdgeUbuntuFirmware.md
- linux/source/firmware/Vim1UbuntuFirmware.md
- linux/source/firmware/Vim2UbuntuFirmware.md
- linux/source/firmware/Vim3UbuntuFirmware.md
- linux/source/firmware/Vim3lUbuntuFirmware.md
- linux/source/zh-cn/firmware/EdgeUbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim1UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim2UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim3UbuntuFirmware.md
- linux/source/zh-cn/firmware/Vim3lUbuntuFirmware.md
Signed-off-by: Yan Wang <frank@khadas.com>
> docs: linux: update VIM1/VIM2/VIM3/VIM3L/Edge firmware
